Repository aquarist-labs/s3gw, pull requests merged in 2023-06, with the labels that each got.

#571 docs: update compatibility matrix
  docs/s3-compatibility-table.md
Labels: kind/documentation

#573 docs: fix bug in compatibility matrix
  docs/s3-compatibility-table.md
Labels: kind/bug, kind/documentation

#579 docs: link release notes v0.15 to v0.17
  mkdocs.yml
Labels: kind/bug, kind/documentation, kind/quality

#589 Docs: update the compatibility table
  docs/s3-compatibility-table.md
Labels: kind/documentation
