Repository aquarist-labs/s3gw, pull requests merged in 2023-05, with the labels that each got.

#489 ci: fix nightly workflow's docker and test
  .github/workflows/nightly.yaml
Labels: area/tests, area/CI

#498 add documentation for COSI deployment via Helm chart
  docs/dicts/s3gw.dict
  docs/helm-charts.md
Labels: kind/documentation, area/kubernetes

#531 ci: nightly pipeline fix trigger
  .github/workflows/nightly.yaml
Labels: area/CI

#510 Add UI testing step in release process ADR
  docs/decisions/0007-release-process.md
Labels: kind/documentation

#549 Update s3gw logos
  assets/images/favicon.svg
  assets/images/s3gw-logo.png
  assets/images/s3gw-logo.svg
Labels: kind/design
