Repository aquarist-labs/s3gw, pull requests merged in 2023-09, with the labels that each got.

#697 Add decision about versioning of the UI REST API
  docs/decisions/0014-ui-backend-api.md
Labels: kind/documentation, area/ui

#654 tools: fix nginx config
  nginx.conf
Labels: kind/quality, area/containers

#713 Dockerfile: drop libsqliteorm
  Dockerfile
  tools/build/Dockerfile.build-radosgw
  tools/build/Dockerfile.s3gw
Labels: DNM
