Repository aquarist-labs/s3gw, pull requests merged in 2023-08, with the labels that each got.

#648 Dockerfile: provide gtest and gmock librires
  Dockerfile
Labels: area/containers, area/CI

#649 ci: unittest container
  Dockerfile
Labels: area/tests, area/containers, area/CI

#661 Docs: update ADR link
  docs/decisions/0007-release-process.md
Labels: kind/documentation

#673 ADR: document using POST instead of GET for some s3gw-ui backend operations
  docs/decisions/0013-ui-backend.md
  docs/decisions/0014-ui-backend-api.md
Labels: kind/documentation, area/ui
