Repository aquarist-labs/s3gw, pull requests merged in 2023-07, with the labels that each got.

#605 Combine duplicate entries in .editorconfig
  .editorconfig
Labels: kind/bug

#528 tools: Add s3tests runner and analysis tools
  .flake8
  .pre-commit-config.yaml
  tools/s3tests/Dockerfile
  tools/s3tests/analyze.py
  tools/s3tests/metadata.yml
  tools/s3tests/requirements.txt
  tools/s3tests/runner.py
  tools/s3tests/s3tr.py
  tools/s3tests/setup
  tools/s3tests/to_sqlite.py
Labels: kind/quality, area/tests

#619 ci: build s3tr tool
  .github/workflows/build-s3tr.yaml
  tools/s3tests/Dockerfile
Labels: kind/enhancement, area/tests, kind/feature, area/CI

#620 ci: fix indentation in build-s3tr.yaml
  .github/workflows/build-s3tr.yaml
Labels: kind/bug, area/tests, area/CI

#621 ci: authenticate against ghcr.io
  .github/workflows/build-s3tr.yaml
Labels: area/tests, area/CI

#631 ADR: SFS Error Handling
  docs/decisions/0012-sfs-error-handling.md
  docs/dicts/errno.dict
  docs/dicts/s3gw.dict
Labels: kind/design, area/rgw-sfs

#640 docs: fix a few things
  CONTRIBUTING.md
  docs/config-s3gw.md
  docs/developing.md
  docs/index.md
  docs/s3gw-repos.md
  tools/env/setup.sh
Labels: kind/documentation, kind/quality
