Repository aquarist-labs/s3gw, pull requests merged in 2023-10, with the labels that each got.

#729 Dockerfile: fix sqlite version to 3.43.1
  Dockerfile
Labels: kind/enhancement, area/containers

#704 Add latest release notes & ADRs to documentation
  mkdocs.yml
Labels: kind/documentation

#700 s3tr enhancements
  tools/s3tests/analyze.py
  tools/s3tests/runner.py
  tools/s3tests/to_sqlite.py
Labels: area/CI

#760 s3tr: Ensure we print the important analyze summary info
  tools/s3tests/analyze.py
  tools/s3tests/s3tr.py
Labels: area/CI

#685 add High Availability research
  .gitignore
  docs/dicts/s3gw.dict
  docs/research/ha/RATIONALE.md
  docs/research/ha/measurements/regular-localhost-incremental-fill-5k/regular-localhost-incremental-fill-5k_percentiles_fup_main_delta_1694534032.svg
  docs/research/ha/measurements/regular-localhost-incremental-fill-5k/regular-localhost-incremental-fill-5k_percentiles_to_fup_1694534032.svg
  docs/research/ha/measurements/regular-localhost-incremental-fill-5k/regular-localhost-incremental-fill-5k_percentiles_to_main_1694534032.svg
  docs/research/ha/measurements/regular-localhost-incremental-fill-5k/regular-localhost-incremental-fill-5k_raw_1694534032.svg
  docs/research/ha/measurements/regular-localhost-incremental-fill-5k/regular-localhost-incremental-fill-5k_stats_1694534032.json
  docs/research/ha/measurements/regular_localhost_load_fio_64_write/regular-localhost-writeload_percentiles_fup_main_delta_1694440297.svg
  docs/research/ha/measurements/regular_localhost_load_fio_64_write/regular-localhost-writeload_percentiles_to_fup_1694440297.svg
  docs/research/ha/measurements/regular_localhost_load_fio_64_write/regular-localhost-writeload_percentiles_to_main_1694440297.svg
  docs/research/ha/measurements/regular_localhost_load_fio_64_write/regular-localhost-writeload_raw_1694440297.svg
  docs/research/ha/measurements/regular_localhost_load_fio_64_write/regular-localhost-writeload_stats_1694440297.json
  docs/research/ha/measurements/regular_localhost_zeroload_400_800Kdb/README.md
  docs/research/ha/measurements/regular_localhost_zeroload_400_800Kdb/regular-localhost-zeroload-400Kdb_percentiles_fup_main_delta_1694522179.svg
  docs/research/ha/measurements/regular_localhost_zeroload_400_800Kdb/regular-localhost-zeroload-400Kdb_percentiles_to_fup_1694522179.svg
  docs/research/ha/measurements/regular_localhost_zeroload_400_800Kdb/regular-localhost-zeroload-400Kdb_percentiles_to_main_1694522179.svg
  docs/research/ha/measurements/regular_localhost_zeroload_400_800Kdb/regular-localhost-zeroload-400Kdb_raw_1694522179.svg
  docs/research/ha/measurements/regular_localhost_zeroload_400_800Kdb/regular-localhost-zeroload-400Kdb_stats_1694522179.json
  docs/research/ha/measurements/regular_localhost_zeroload_400_800Kdb/regular-localhost-zeroload-800Kdb_percentiles_fup_main_delta_1694524508.svg
  docs/research/ha/measurements/regular_localhost_zeroload_400_800Kdb/regular-localhost-zeroload-800Kdb_percentiles_to_fup_1694524508.svg
  docs/research/ha/measurements/regular_localhost_zeroload_400_800Kdb/regular-localhost-zeroload-800Kdb_percentiles_to_main_1694524508.svg
  docs/research/ha/measurements/regular_localhost_zeroload_400_800Kdb/regular-localhost-zeroload-800Kdb_raw_1694524508.svg
  docs/research/ha/measurements/regular_localhost_zeroload_emptydb/regular-localhost-zeroload-emptydb_percentiles_fup_main_delta_1694425886.svg
  docs/research/ha/measurements/regular_localhost_zeroload_emptydb/regular-localhost-zeroload-emptydb_percentiles_to_fup_1694425886.svg
  docs/research/ha/measurements/regular_localhost_zeroload_emptydb/regular-localhost-zeroload-emptydb_percentiles_to_main_1694425886.svg
  docs/research/ha/measurements/regular_localhost_zeroload_emptydb/regular-localhost-zeroload-emptydb_raw_1694425886.svg
  docs/research/ha/measurements/regular_localhost_zeroload_emptydb/regular-localhost-zeroload-emptydb_stats_1694425886.json
  docs/research/ha/measurements/s3wl-putobj-100ms-clusterip/1695396383_s3wl-putobj-100ms-ClusterIp_S3WL_RTT_raw.svg
  docs/research/ha/measurements/s3wl-putobj-100ms-clusterip/1695396383_s3wl-putobj-100ms-ClusterIp_percentiles_fup_main_delta.svg
  docs/research/ha/measurements/s3wl-putobj-100ms-clusterip/1695396383_s3wl-putobj-100ms-ClusterIp_percentiles_to_fup.svg
  docs/research/ha/measurements/s3wl-putobj-100ms-clusterip/1695396383_s3wl-putobj-100ms-ClusterIp_percentiles_to_main.svg
  docs/research/ha/measurements/s3wl-putobj-100ms-clusterip/1695396383_s3wl-putobj-100ms-ClusterIp_raw.svg
  docs/research/ha/measurements/s3wl-putobj-100ms-clusterip/1695396383_s3wl-putobj-100ms-ClusterIp_stats.json
  docs/research/ha/measurements/s3wl-putobj-100ms-ingress/1695396145_s3wl-putobj-100ms-Ingress_S3WL_RTT_raw.svg
  docs/research/ha/measurements/s3wl-putobj-100ms-ingress/1695396145_s3wl-putobj-100ms-Ingress_percentiles_fup_main_delta.svg
  docs/research/ha/measurements/s3wl-putobj-100ms-ingress/1695396145_s3wl-putobj-100ms-Ingress_percentiles_to_fup.svg
  docs/research/ha/measurements/s3wl-putobj-100ms-ingress/1695396145_s3wl-putobj-100ms-Ingress_percentiles_to_main.svg
  docs/research/ha/measurements/s3wl-putobj-100ms-ingress/1695396145_s3wl-putobj-100ms-Ingress_raw.svg
  docs/research/ha/measurements/s3wl-putobj-100ms-ingress/1695396145_s3wl-putobj-100ms-Ingress_stats.json
  docs/research/ha/measurements/scale_deployment_0_1-k3s3nodes-zeroload-emptydb/scale_deployment_0_1-k3s3nodes-zeroload-emptydb_percentiles_fup_main_delta_1695046129.svg
  docs/research/ha/measurements/scale_deployment_0_1-k3s3nodes-zeroload-emptydb/scale_deployment_0_1-k3s3nodes-zeroload-emptydb_percentiles_to_fup_1695046129.svg
  docs/research/ha/measurements/scale_deployment_0_1-k3s3nodes-zeroload-emptydb/scale_deployment_0_1-k3s3nodes-zeroload-emptydb_percentiles_to_main_1695046129.svg
  docs/research/ha/measurements/scale_deployment_0_1-k3s3nodes-zeroload-emptydb/scale_deployment_0_1-k3s3nodes-zeroload-emptydb_raw_1695046129.svg
  docs/research/ha/measurements/scale_deployment_0_1-k3s3nodes-zeroload-emptydb/scale_deployment_0_1-k3s3nodes-zeroload-emptydb_stats_1695046129.json
  docs/research/ha/measurements/segfault_localhost_zeroload_emptydb/segfault-localhost-zeroload-emptydb_percentiles_fup_main_delta_1694428197.svg
  docs/research/ha/measurements/segfault_localhost_zeroload_emptydb/segfault-localhost-zeroload-emptydb_percentiles_to_fup_1694428197.svg
  docs/research/ha/measurements/segfault_localhost_zeroload_emptydb/segfault-localhost-zeroload-emptydb_percentiles_to_main_1694428197.svg
  docs/research/ha/measurements/segfault_localhost_zeroload_emptydb/segfault-localhost-zeroload-emptydb_raw_1694428197.svg
  docs/research/ha/measurements/segfault_localhost_zeroload_emptydb/segfault-localhost-zeroload-emptydb_stats_1694428197.json
Labels: kind/research, area/kubernetes, area/rgw-sfs

#780 ci: nightly UI builds
  .github/workflows/nightly-ui.yaml
Labels: area/ui, area/containers, area/CI

#733 Add decision about the HA model to be used with the s3gw with Longhorn
  docs/decisions/0018-s3gw-ha-model.md
Labels: kind/research, area/kubernetes

#757 docs/ideas: define PID records
  docs/ideas/PID-0-reserved.md
Labels: area/docs

#783 ci: run unittests in the nightly test suite
  .github/workflows/nightly.yaml
Labels: area/tests, area/CI

#776 docs: Mark SSE partially supported
  docs/s3-compatibility-table.md
Labels: area/docs
