Repository aquarist-labs/s3gw, pull requests merged in 2023-02, with the labels that each got.

#332 Add last ADRs to menu in docs
  mkdocs.yml
Labels: kind/documentation

#342 Fix (relative) path to s3gw-ui Git repository.
  tools/build-ui/build.sh
Labels: kind/bug

#346 ci: rebuild build environments weekly
  .github/workflows/build-environment.yaml
Labels: area/CI

#348 ci: on-disk format checker and release tests
  .github/workflows/release.yaml
  tools/tests/on-disk-format-checker.sh
Labels: kind/design, kind/quality, area/tests, area/CI

#353 ci: fix s3test runner script
  tools/tests/s3tests-runner.sh
Labels: area/tests, area/CI
